### ISSUE TITLE
02c: def pipeline() gives Attribute Error.

### ISSUE THREAD

**Issue by JonB451** [statmike/vertex-ai-mlops#53]
`AttributeError: module 'google.cloud.aiplatform' has no attribute 'TabularDatasetCreateOp'
`

**Comment by JonB451** [comment]
This comes from 
`dataset = gcc_aip.TabularDatasetCreateOp(
`    
Have tried changing to:
`dataset = gcc_aip.datasets.TabularDataset.create(
`

but this gives later error:

`TypeError: object of type 'PipelineParameterChannel' has no len()
`

**Comment by statmike** [comment]
Hello @JonB451 
Apologies for the delay here.  I took at look at issue #51 and reopened it to address the update I just pushed that should resolve the import of the components.  This was due to a shift in the SDK since I originally made the notebook.  This fix should also address the issue you are facing here in #53 .

Thank you for pointing this out!
@statmike

**Comment by JonB451** [comment]
Thanks @statmike . I've had to move onto something else for now, but will let you know when i get back to this. It's still high enough up my priorities that i hope that should be possible in the coming weeks so i will feedback if it worked here too. Thanks again, loads. You are a brilliant teacher, and generours, in material and in spirit it seems!
